import type { MidiBinding } from "../audio/types";

/** Punto de partida estilo Mixtrack. Ajusta con MIDI Learn si tu modelo difiere. */
export const NUMARK_STARTER: MidiBinding[] = [
  { target: "deck.a.play", type: "note", channel: 1, data: 59 },
  { target: "deck.a.cue", type: "note", channel: 1, data: 51 },
  { target: "deck.a.sync", type: "note", channel: 1, data: 64 },
  { target: "deck.a.load", type: "note", channel: 1, data: 75 },
  { target: "deck.b.play", type: "note", channel: 1, data: 66 },
  { target: "deck.b.cue", type: "note", channel: 1, data: 60 },
  { target: "deck.b.sync", type: "note", channel: 1, data: 71 },
  { target: "deck.b.load", type: "note", channel: 1, data: 83 },
  { target: "mixer.crossfader", type: "cc", channel: 1, data: 8 },
  { target: "deck.a.volume", type: "cc", channel: 1, data: 14 },
  { target: "deck.b.volume", type: "cc", channel: 1, data: 15 },
  { target: "deck.a.jog", type: "cc", channel: 1, data: 25 },
  { target: "deck.b.jog", type: "cc", channel: 1, data: 24 },
  { target: "deck.a.pitch", type: "cc", channel: 1, data: 13 },
  { target: "deck.b.pitch", type: "cc", channel: 1, data: 12 },
  { target: "deck.a.hotcue.0", type: "note", channel: 1, data: 20 },
  { target: "deck.a.hotcue.1", type: "note", channel: 1, data: 21 },
  { target: "deck.a.hotcue.2", type: "note", channel: 1, data: 22 },
  { target: "deck.a.hotcue.3", type: "note", channel: 1, data: 23 },
  { target: "library.up", type: "note", channel: 1, data: 48 },
  { target: "library.down", type: "note", channel: 1, data: 49 },
];

/** Genérico de 2 canales: notas 1-16 en canal 1, CC 1-16 para mandos. */
const GENERIC_2CH: MidiBinding[] = [
  { target: "deck.a.play", type: "note", channel: 1, data: 1 },
  { target: "deck.a.cue", type: "note", channel: 1, data: 2 },
  { target: "deck.a.sync", type: "note", channel: 1, data: 3 },
  { target: "deck.a.load", type: "note", channel: 1, data: 4 },
  { target: "deck.b.play", type: "note", channel: 1, data: 5 },
  { target: "deck.b.cue", type: "note", channel: 1, data: 6 },
  { target: "deck.b.sync", type: "note", channel: 1, data: 7 },
  { target: "deck.b.load", type: "note", channel: 1, data: 8 },
  { target: "deck.a.hotcue.0", type: "note", channel: 1, data: 36 },
  { target: "deck.a.hotcue.1", type: "note", channel: 1, data: 37 },
  { target: "deck.a.hotcue.2", type: "note", channel: 1, data: 38 },
  { target: "deck.a.hotcue.3", type: "note", channel: 1, data: 39 },
  { target: "deck.b.hotcue.0", type: "note", channel: 1, data: 40 },
  { target: "deck.b.hotcue.1", type: "note", channel: 1, data: 41 },
  { target: "deck.b.hotcue.2", type: "note", channel: 1, data: 42 },
  { target: "deck.b.hotcue.3", type: "note", channel: 1, data: 43 },
  { target: "mixer.crossfader", type: "cc", channel: 1, data: 1 },
  { target: "mixer.master", type: "cc", channel: 1, data: 2 },
  { target: "deck.a.volume", type: "cc", channel: 1, data: 3 },
  { target: "deck.b.volume", type: "cc", channel: 1, data: 4 },
  { target: "deck.a.pitch", type: "cc", channel: 1, data: 5 },
  { target: "deck.b.pitch", type: "cc", channel: 1, data: 6 },
  { target: "deck.a.gain", type: "cc", channel: 1, data: 7 },
  { target: "deck.b.gain", type: "cc", channel: 1, data: 8 },
  { target: "deck.a.eqHigh", type: "cc", channel: 1, data: 9 },
  { target: "deck.a.eqMid", type: "cc", channel: 1, data: 10 },
  { target: "deck.a.eqLow", type: "cc", channel: 1, data: 11 },
  { target: "deck.b.eqHigh", type: "cc", channel: 1, data: 12 },
  { target: "deck.b.eqMid", type: "cc", channel: 1, data: 13 },
  { target: "deck.b.eqLow", type: "cc", channel: 1, data: 14 },
  { target: "deck.a.filter", type: "cc", channel: 1, data: 15 },
  { target: "deck.b.filter", type: "cc", channel: 1, data: 16 },
  { target: "deck.a.jog", type: "cc", channel: 1, data: 20 },
  { target: "deck.b.jog", type: "cc", channel: 1, data: 21 },
  { target: "library.up", type: "note", channel: 1, data: 50 },
  { target: "library.down", type: "note", channel: 1, data: 51 },
  { target: "preview.toggle", type: "note", channel: 1, data: 52 },
];

/** Pioneer DDJ-style: play/cue por canal MIDI del deck (ch1 / ch2). Aproximado. */
const PIONEER_DDJ: MidiBinding[] = [
  { target: "deck.a.play", type: "note", channel: 1, data: 11 },
  { target: "deck.a.cue", type: "note", channel: 1, data: 12 },
  { target: "deck.a.sync", type: "note", channel: 1, data: 88 },
  { target: "deck.b.play", type: "note", channel: 2, data: 11 },
  { target: "deck.b.cue", type: "note", channel: 2, data: 12 },
  { target: "deck.b.sync", type: "note", channel: 2, data: 88 },
  { target: "mixer.crossfader", type: "cc", channel: 7, data: 31 },
  { target: "deck.a.volume", type: "cc", channel: 1, data: 19 },
  { target: "deck.b.volume", type: "cc", channel: 2, data: 19 },
  { target: "deck.a.pitch", type: "cc", channel: 1, data: 0 },
  { target: "deck.b.pitch", type: "cc", channel: 2, data: 0 },
  { target: "deck.a.eqHigh", type: "cc", channel: 1, data: 7 },
  { target: "deck.a.eqMid", type: "cc", channel: 1, data: 11 },
  { target: "deck.a.eqLow", type: "cc", channel: 1, data: 15 },
  { target: "deck.b.eqHigh", type: "cc", channel: 2, data: 7 },
  { target: "deck.b.eqMid", type: "cc", channel: 2, data: 11 },
  { target: "deck.b.eqLow", type: "cc", channel: 2, data: 15 },
  { target: "deck.a.filter", type: "cc", channel: 6, data: 23 },
  { target: "deck.b.filter", type: "cc", channel: 6, data: 24 },
  { target: "deck.a.jog", type: "cc", channel: 1, data: 34 },
  { target: "deck.b.jog", type: "cc", channel: 2, data: 34 },
];

export const MIDI_PRESETS: { id: string; label: string; bindings: MidiBinding[] }[] = [
  { id: "generic", label: "Genérico 2 canales", bindings: GENERIC_2CH },
  { id: "numark", label: "Numark Mixtrack", bindings: NUMARK_STARTER },
  { id: "pioneer", label: "Pioneer DDJ (aprox.)", bindings: PIONEER_DDJ },
];
